[tool.poetry]
name = "cats_and_dogs"
version = "0.1.0"
description = "MLOps example"
authors = ["Vladislav Naumov <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fire = "^0.7.0"
torch = "^2.5.0"
torchvision = "^0.20.1"
pytorch-lightning = "^2.4.0"
pandas="^2.0.0"
requests="*"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.0.1"

[tool.isort]
src_paths = ["cats_and_dogs"]
profile = "black"
line_length = 90
lines_after_imports = 2

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
